/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
